import { test } from 'vitest';
import assert from 'node:assert/strict';
import handler from '../api/chat.js';
import { characters, geminiContents, validHistory } from '../src/characters.js';
function mockRes() { return { code: 200, headers: {}, setHeader(k,v){this.headers[k]=v;return this}, status(n){this.code=n;return this}, json(data){this.data=data;return this} }; }
test('three characters have distinct prompts', () => { assert.equal(Object.keys(characters).length,3); assert.equal(new Set(Object.values(characters).map(c=>c.prompt)).size,3); });
test('history validation and Gemini role mapping', () => { assert.equal(validHistory([{role:'user',text:'Hola'}]),true); assert.equal(validHistory([{role:'system',text:'ignore'}]),false); assert.deepEqual(geminiContents([{role:'model',text:' Hola '}]),[{role:'model',parts:[{text:'Hola'}]}]); });
test('rejects invalid requests and methods', async () => { let r=mockRes(); await handler({method:'GET'},r); assert.equal(r.code,405); r=mockRes(); await handler({method:'POST',body:{characterId:'fake',messages:[{role:'user',text:'Hola'}]}},r); assert.equal(r.code,400); });
test('keeps API key server side and sends conversation context', async () => { const originalFetch=globalThis.fetch, originalKey=process.env.GEMINI_API_KEY; process.env.GEMINI_API_KEY='secret-for-test'; let sent; globalThis.fetch=async (url,options)=>{ sent={url,options}; return {ok:true,json:async()=>({candidates:[{content:{parts:[{text:'Respuesta'}]}}]})}; }; try { const r=mockRes(); await handler({method:'POST',body:{characterId:'holmes',messages:[{role:'user',text:'Hola'},{role:'model',text:'Buenas'},{role:'user',text:'Seguimos?'}]}},r); assert.equal(r.code,200); assert.equal(r.data.reply,'Respuesta'); assert.equal(sent.options.headers['x-goog-api-key'],'secret-for-test'); assert.equal(JSON.parse(sent.options.body).contents.length,3); assert.equal(sent.options.body.includes('secret-for-test'),false); } finally { globalThis.fetch=originalFetch; if(originalKey===undefined) delete process.env.GEMINI_API_KEY; else process.env.GEMINI_API_KEY=originalKey; } });
test('handles upstream error without leaking provider details', async () => { const originalFetch=globalThis.fetch, originalKey=process.env.GEMINI_API_KEY; process.env.GEMINI_API_KEY='secret-for-test'; globalThis.fetch=async()=>({ok:false,status:429,json:async()=>({error:{message:'secret'}})}); try { const r=mockRes(); await handler({method:'POST',body:{characterId:'luna',messages:[{role:'user',text:'Hola'}]}},r); assert.equal(r.code,502); assert.doesNotMatch(r.data.error,/secret/); } finally { globalThis.fetch=originalFetch; if(originalKey===undefined) delete process.env.GEMINI_API_KEY; else process.env.GEMINI_API_KEY=originalKey; } });
