import { characters } from './characters.js';
const app = document.querySelector('#app');
const state = { characterId: 'holmes', chats: {}, busy: false, error: '', theme: localStorage.getItem('entre-theme') === 'light' ? 'light' : 'dark' };
try { const saved = JSON.parse(localStorage.getItem('entre-chats') || '{}'); for (const id of Object.keys(characters)) if (Array.isArray(saved[id])) state.chats[id] = saved[id].filter(m => m && ['user','model'].includes(m.role) && typeof m.text === 'string').slice(-24); } catch { /* ignore broken saved data */ }
const escapeHTML = value => String(value).replace(/[&<>"']/g, c => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' })[c]);
const save = () => { try { localStorage.setItem('entre-chats', JSON.stringify(state.chats)); } catch { state.error = 'No se pudo guardar el historial en este navegador.'; } };
const path = () => ['/home','/chat','/about'].includes(location.pathname) ? location.pathname : '/home';
function navigate(to) { if (location.pathname !== to) history.pushState({}, '', to); state.error = ''; render(); window.scrollTo(0,0); }
function card(id) { const c = characters[id]; return `<button class="character-card ${state.characterId===id?'selected':''}" data-character="${id}" style="--accent:${c.accent}"><span class="card-icon" aria-hidden="true">${c.icon}</span><span><strong>${c.name}</strong><small>${c.role}</small></span><span class="card-arrow" aria-hidden="true">↗</span></button>`; }
function home() { return `<section class="hero"><div class="eyebrow"><span class="spark">✳</span> UN PORTAL A OTRAS HISTORIAS</div><h1>Una charla fuera<br>de <em>este mundo.</em></h1><p>Elegí a quién querés conocer. Una conversación nueva puede empezar con una sola pregunta.</p><a class="primary" href="/chat" data-link>Empezar a charlar <span aria-hidden="true">↗</span></a><div class="hero-orb" aria-hidden="true"><span>✦</span><span>✧</span><span>✳</span></div></section><section class="section"><div class="section-heading"><div><span class="kicker">EL ELENCO</span><h2>Tres mundos, una pregunta</h2></div><p>Elegí tu próxima conversación</p></div><div class="cards">${Object.keys(characters).map(card).join('')}</div></section>`; }
function chat() { const c = characters[state.characterId], messages = state.chats[state.characterId] || []; return `<section class="chat-layout"><aside class="chat-sidebar"><span class="kicker">ELEGÍ TU PERSONAJE</span><h2>¿Con quién hablamos?</h2><div class="cards">${Object.keys(characters).map(card).join('')}</div><div class="sidebar-note">✦ Cada personaje recuerda su propia conversación en este navegador.</div></aside><section class="chat-panel" style="--accent:${c.accent}" aria-label="Conversación con ${c.name}"><div class="chat-header"><div class="avatar">${c.icon}</div><div class="chat-person"><strong>${c.name}</strong><span><i></i> ${c.role}</span></div><button class="clear-button" id="clear" ${messages.length?'':'disabled'} title="Borrar historial" aria-label="Borrar historial con ${c.name}">Borrar chat</button></div><div class="messages" id="messages" role="log" aria-live="polite" aria-relevant="additions"><div class="day-marker">UN NUEVO ENCUENTRO</div>${messages.length ? messages.map((m,i) => `<div class="message ${m.role==='user'?'mine':'theirs'}"><div class="bubble">${escapeHTML(m.text).replace(/\n/g,'<br>')}</div><div class="message-meta"><time datetime="${escapeHTML(m.at||'')}">${m.at ? new Date(m.at).toLocaleTimeString('es-AR',{hour:'2-digit',minute:'2-digit'}) : ''}</time>${m.role==='model'?`<button class="copy" data-copy="${i}" aria-label="Copiar respuesta">Copiar ↗</button>`:''}</div></div>`).join('') : `<div class="empty"><span class="empty-icon">${c.icon}</span><h3>La conversación empieza acá.</h3><p>${c.intro}</p></div>`}${state.busy ? '<div class="message theirs"><div class="bubble typing" aria-label="Escribiendo"><span></span><span></span><span></span></div></div>':''}</div><form id="chat-form"><div class="composer"><label class="sr-only" for="message-input">Escribí tu mensaje</label><input id="message-input" autocomplete="off" maxlength="2000" placeholder="Escribí tu mensaje..." ${state.busy?'disabled':''} required><button type="submit" ${state.busy?'disabled':''} aria-label="Enviar mensaje">↗</button></div><div class="compose-bottom"><span>Enter para enviar</span><span>${messages.length ? '● Historial guardado' : 'Una historia por comenzar'}</span></div>${state.error?`<p class="error" role="alert">${escapeHTML(state.error)}</p>`:''}</form></section></section>`; }
function about() { return `<section class="about"><span class="kicker">DETRÁS DEL PORTAL</span><h1>Historias que<br><em>te responden.</em></h1><p>Entre mundos es un pequeño experimento para conversar con personajes ficticios. Cada uno tiene su propia voz y recuerda los mensajes anteriores durante la charla.</p><div class="about-grid"><article><span>01 / IMAGINACIÓN</span><h2>Tres voces distintas</h2><p>Un detective, una astrónoma y una hechicera: elegí la historia que querés explorar.</p></article><article><span>02 / TECNOLOGÍA</span><h2>Impulsado por Gemini</h2><p>La respuesta se genera con IA. Los personajes son ficción y pueden equivocarse.</p></article><article><span>03 / PRIVACIDAD</span><h2>Tu chat, tu navegador</h2><p>El historial se guarda localmente y podés borrarlo cuando quieras. Se envía a Gemini el contexto necesario para responder.</p></article></div><a class="primary" href="/chat" data-link>Ir al chat <span aria-hidden="true">↗</span></a></section>`; }
function render() { document.documentElement.dataset.theme = state.theme; const current = path(); document.title = `${current==='/chat'?'Chat':current==='/about'?'Acerca de':'Inicio'} | Entre mundos`; app.innerHTML = `<header class="site-header"><a href="/home" data-link class="brand"><span class="brand-mark">✳</span> ENTRE MUNDOS<span class="brand-dot">.</span></a><nav aria-label="Navegación principal"><a href="/home" data-link ${current==='/home'?'aria-current="page"':''}>Inicio</a><a href="/chat" data-link ${current==='/chat'?'aria-current="page"':''}>Chat</a><a href="/about" data-link ${current==='/about'?'aria-current="page"':''}>Acerca de</a></nav><button id="theme-toggle" class="theme-toggle" aria-label="Cambiar a modo ${state.theme==='dark'?'claro':'oscuro'}">${state.theme==='dark'?'☼':'☾'}</button></header><main>${current==='/chat'?chat():current==='/about'?about():home()}</main><footer><span>✳ ENTRE MUNDOS</span><span>Un espacio para imaginar, conversar y descubrir.</span><span>Hecho con curiosidad ✦</span></footer>`; if(current==='/chat') scrollBottom(); }
function scrollBottom() { const node=document.querySelector('#messages'); if(node) node.scrollTop=node.scrollHeight; }
app.addEventListener('click', e => { const link=e.target.closest('[data-link]'); if(link) { e.preventDefault(); navigate(link.getAttribute('href')); return; } const chosen=e.target.closest('[data-character]'); if(chosen) { state.characterId=chosen.dataset.character; state.error=''; if(path()!=='/chat') navigate('/chat'); else render(); return; } if(e.target.closest('#theme-toggle')) { state.theme=state.theme==='dark'?'light':'dark'; localStorage.setItem('entre-theme',state.theme); render(); return; } if(e.target.closest('#clear')) { if(state.busy) return; state.chats[state.characterId]=[]; save(); state.error=''; render(); return; } const copy=e.target.closest('[data-copy]'); if(copy) { const msg=state.chats[state.characterId]?.[Number(copy.dataset.copy)]; if(msg) navigator.clipboard.writeText(msg.text).then(()=>{copy.textContent='¡Copiado!'}).catch(()=>{state.error='No se pudo copiar el texto.';render()}); } });
app.addEventListener('submit', async e => { if(e.target.id!=='chat-form') return; e.preventDefault(); if(state.busy) return; const input=e.target.querySelector('input'); const text=input.value.trim(); if(!text) return; const id=state.characterId; const history=state.chats[id] ||= []; history.push({role:'user',text,at:new Date().toISOString()}); state.busy=true; state.error=''; render(); try { const response=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({characterId:id,messages:history.slice(-24).map(({role,text})=>({role,text}))})}); const data=await response.json(); if(!response.ok || !data.reply) throw new Error(data.error||'No se recibió una respuesta.'); history.push({role:'model',text:data.reply,at:new Date().toISOString()}); save(); } catch(err) { history.pop(); state.error=err.message||'No se pudo enviar el mensaje.'; } finally { state.busy=false; render(); if(state.error) { const field=document.querySelector('#message-input'); if(field && state.characterId===id) { field.value=text; field.focus(); } } } });
window.addEventListener('popstate', render);
if(location.pathname==='/') history.replaceState({},'', '/home');
render();
